services:
  - type: web
    name: proctoring-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 wsgi:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /
